
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = taomerit.c dlregis_taomerit.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetsctao
MANSEC    = Tao
SUBMANSEC = TaoMerit
LOCDIR    = src/tao/merit/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


