-include ../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = ex1.c
SOURCEF   =
SOURCEH   = 
DIRS      = 
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = NRS
LOCDIR    = src/dm/dt/netrs/tests

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

