-include ../../../petscdir.mk
ALL: lib

SOURCEH   = ../../../include/petsc/private/mlregressorimpl.h ../../../include/petscmlregressor.h
DIRS      = interface impls tests tutorials
LOCDIR    = src/ml/regressor/
MANSEC    = ML
SUBMANSEC = Regressor

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
