
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mpomin.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscksp
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/gcr/mpomin/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
