-include ../../../petscdir.mk
ALL: lib

SOURCEH   = ../../../include/petsc/private/mldrimpl.h ../../../include/petscmldr.h
DIRS      = interface impls tests tutorials
LOCDIR    = src/ml/dr/
MANSEC    = ML
SUBMANSEC = MLDR

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
