-include ../../../petscdir.mk
#requiresdefine   'PETSC_USE_FORTRAN_BINDINGS'

LIBBASE    = libpetscml
MANSEC     = ML
SUBMANSEC  = PetscRegressor
CLEANFILES = *.mod

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
