-include ../../../../../petsckdir.mk
#requiresdefine 'PETSC_HAVE_CXX'

SOURCECXX = dcontext.cxx device.cxx devicereg.cxx managedtype_cxx.cxx memory.cxx
SOURCEH   = managedtype.inl
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/objects/device/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

