-include ../../../../../petsckdir.mk

SOURCEC   = devicereg.c managedtype_c.c
SOURCECXX = dcontext.cxx device.cxx managedtype_cxx.cxx
SOURCEH   = objpool.hpp managedtype.inl
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/objects/device/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

