-include ../../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = linearized.c linearized_star.c
SOURCEF   =
SOURCEH   =
DIRS      = 
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = NRS
LOCDIR    = src/dm/dt/netrs/impls/linearized

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test