-include ../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = dr.c mldrregi.c dlregismldr.c
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscml
MANSEC    = ML
SUBMANSEC = MLDR
LOCDIR    = src/ml/dr/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
