
#requirespackage 	'PETSC_HAVE_FORTRAN'
ALL: lib
CFLAGS=
FFLAGS=
SOURCEC=zbnkf.c
SOURCEF=
SOURCEH=
DIR=
LIBBASE=libpetsctao
LOCDIR=src/tao/bound/impls/bnk/ftn-custom

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test 
