-include ../../../../../../petscdir.mk

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = diagbb.c
SOURCEF  =
SOURCEH  = diagbb.h
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/utils/lmvm/diagbb/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
