

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = cdbfgs.c
SOURCEF  =
SOURCEH  = cdbfgs.h
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/utils/lmvm/cdbfgs/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
