-include ../../../../../petscdir.mk
ALL: lib

SOURCEC   = 
SOURCEH   = ../../../../include/petsc/private/localnetrpimpl.h ../../../../include/petscnetrp.h
DIRS      = interface impls tests
LOCDIR    = src/dm/dt/netrs/localnetrp
MANSEC    = DM
SUBMANSEC = NRS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

