!
!
!  Include file for Fortran use of the PetscFn package in PETSc
!
#include "petsc/finclude/petscfn.h"

      type tPetscFn
        sequence
        PetscFortranAddr:: v PETSC_FORTRAN_TYPE_INITIALIZE
      end type tPetscFn
!
! PetscFnOperation
!
      PetscEnum PETSCFNOP_CREATEVECS
      PetscEnum PETSCFNOP_APPLY
      PetscEnum PETSCFNOP_DERIVATIVESCALAR
      PetscEnum PETSCFNOP_DERIVATIVEVEC
      PetscEnum PETSCFNOP_DERIVATIVEMAT
      PetscEnum PETSCFNOP_DERIVATIVEFN
      PetscEnum PETSCFNOP_SCALARAPPLY
      PetscEnum PETSCFNOP_SCALARDERIVATIVESCALAR
      PetscEnum PETSCFNOP_SCALARDERIVATIVEVEC
      PetscEnum PETSCFNOP_SCALARDERIVATIVEMAT
      PetscEnum PETSCFNOP_SCALARDERIVATIVEFN
      PetscEnum PETSCFNOP_CREATESUBFNS
      PetscEnum PETSCFNOP_DESTROYSUBFNS
      PetscEnum PETSCFNOP_CREATESUBFN
      PetscEnum PETSCFNOP_DESTROY

      parameter(PETSCFNOP_CREATEVECS=0)
      parameter(PETSCFNOP_DERIVATIVESCALAR=1)
      parameter(PETSCFNOP_DERIVATIVEVEC=2)
      parameter(PETSCFNOP_DERIVATIVEMAT=3)
      parameter(PETSCFNOP_DERIVATIVEFN=4)
      parameter(PETSCFNOP_SCALARAPPLY=5)
      parameter(PETSCFNOP_SCALARDERIVATIVESCALAR=5)
      parameter(PETSCFNOP_SCALARDERIVATIVEVEC=6)
      parameter(PETSCFNOP_SCALARDERIVATIVEMAT=7)
      parameter(PETSCFNOP_SCALARDERIVATIVEFN=8)
      parameter(PETSCFNOP_CREATESUBFNS=9)
      parameter(PETSCFNOP_DESTROYSUBFNS=10)
      parameter(PETSCFNOP_CREATESUBFN=11)
      parameter(PETSCFNOP_CREATEDERIVATIVEFN=12)
      parameter(PETSCFNOP_DESTROY=13)
!
!  End of Fortran include file for the PetscFn package in PETSc
!
#if defined(_WIN32) && defined(PETSC_USE_SHARED_LIBRARIES)
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATEVECS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_APPLY
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_DERIVATIVESCALAR
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_DERIVATIVEVEC
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_DERIVATIVEMAT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_DERIVATIVEFN
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARAPPLY
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARDERIVATIVESCALAR
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARDERIVATIVEVEC
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARDERIVATIVEMAT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARDERIVATIVEFN
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATESUBFNS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_DESTROYSUBFNS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATESUBFN
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_DESTROY
#endif
