!
!
!  Include file for Fortran use of the PetscFn package in PETSc
!
#include "petsc/finclude/petscfn.h"

      type tPetscFn
        sequence
        PetscFortranAddr:: v PETSC_FORTRAN_TYPE_INITIALIZE
      end type tPetscFn
!
! PetscFnOperation
!
      PetscEnum PETSCFNOP_CREATE_VECS
      PetscEnum PETSCFNOP_CREATE_MATS
      PetscEnum PETSCFNOP_APPLY
      PetscEnum PETSCFNOP_JACOBIANMULT
      PetscEnum PETSCFNOP_JACOBIANMULTADJOINT
      PetscEnum PETSCFNOP_JACOBIANCREATE
      PetscEnum PETSCFNOP_JACOBIANCREATEADJOINT
      PetscEnum PETSCFNOP_HESSIANMULT
      PetscEnum PETSCFNOP_HESSIANCREATE
      PetscEnum PETSCFNOP_SCALARAPPLY
      PetscEnum PETSCFNOP_SCALARGRADIENT
      PetscEnum PETSCFNOP_SCALARHESSIANMULT
      PetscEnum PETSCFNOP_SCALARHESSIANCREATE
      PetscEnum PETSCFNOP_CREATESUBFNS
      PetscEnum PETSCFNOP_DESTROYSUBFNS
      PetscEnum PETSCFNOP_CREATESUBFN

      parameter(PETSCFNOP_CREATE_VECS=0)
      parameter(PETSCFNOP_CREATE_MATS=1)
      parameter(PETSCFNOP_APPLY=2)
      parameter(PETSCFNOP_JACOBIANMULT=3)
      parameter(PETSCFNOP_JACOBIANMULTADJOINT=4)
      parameter(PETSCFNOP_JACOBIANCREATE=5)
      parameter(PETSCFNOP_JACOBIANCREATEADJOINT=6)
      parameter(PETSCFNOP_HESSIANMULT=7)
      parameter(PETSCFNOP_HESSIANCREATE=8)
      parameter(PETSCFNOP_SCALARAPPLY=9)
      parameter(PETSCFNOP_SCALARGRADIENT=10)
      parameter(PETSCFNOP_SCALARHESSIANMULT=11)
      parameter(PETSCFNOP_SCALARHESSIANCREATE=12)
      parameter(PETSCFNOP_CREATESUBFNS=13)
      parameter(PETSCFNOP_DESTROYSUBFNS=14)
      parameter(PETSCFNOP_CREATESUBFN=15)
!
!  End of Fortran include file for the PetscFn package in PETSc
!
#if defined(_WIN32) && defined(PETSC_USE_SHARED_LIBRARIES)
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATE_VECS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATE_MATS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_APPLY
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_JACOBIANMULT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_JACOBIANMULTADJOINT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_JACOBIANCREATE
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_JACOBIANCREATEADJOINT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_HESSIANMULT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_HESSIANCREATE
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARAPPLY
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARGRADIENT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARHESSIANMULT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARHESSIANCREATE
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATESUBFNS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_DESTROYSUBFNS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATESUBFN
#endif
