!
!
!  Include file for Fortran use of the PetscFn package in PETSc
!
#include "petsc/finclude/petscfn.h"

      type tPetscFn
        sequence
        PetscFortranAddr:: v PETSC_FORTRAN_TYPE_INITIALIZE
      end type tPetscFn
!
! PetscFnOperation
!
      PetscEnum PETSCFNOP_CREATEVECS
      PetscEnum PETSCFNOP_CREATEMATS
      PetscEnum PETSCFNOP_APPLY
      PetscEnum PETSCFNOP_JACOBIANMULT
      PetscEnum PETSCFNOP_JACOBIANMULTADJOINT
      PetscEnum PETSCFNOP_JACOBIANBUILD
      PetscEnum PETSCFNOP_JACOBIANBUILDADJOINT
      PetscEnum PETSCFNOP_HESSIANMULT
      PetscEnum PETSCFNOP_HESSIANMULTADJOINT
      PetscEnum PETSCFNOP_HESSIANBUILD
      PetscEnum PETSCFNOP_HESSIANBUILDADJOINT
      PetscEnum PETSCFNOP_HESSIANBUILDSWAP
      PetscEnum PETSCFNOP_SCALARAPPLY
      PetscEnum PETSCFNOP_SCALARGRADIENT
      PetscEnum PETSCFNOP_SCALARHESSIANMULT
      PetscEnum PETSCFNOP_SCALARHESSIANBUILD
      PetscEnum PETSCFNOP_CREATESUBFNS
      PetscEnum PETSCFNOP_DESTROYSUBFNS
      PetscEnum PETSCFNOP_CREATESUBFN
      PetscEnum PETSCFNOP_CREATEDERIVATIVEFN
      PetscEnum PETSCFNOP_DESTROY

      parameter(PETSCFNOP_CREATEVECS=0)
      parameter(PETSCFNOP_CREATEMATS=1)
      parameter(PETSCFNOP_APPLY=2)
      parameter(PETSCFNOP_JACOBIANMULT=3)
      parameter(PETSCFNOP_JACOBIANMULTADJOINT=4)
      parameter(PETSCFNOP_JACOBIANBUILD=5)
      parameter(PETSCFNOP_JACOBIANBUILDADJOINT=6)
      parameter(PETSCFNOP_HESSIANMULT=7)
      parameter(PETSCFNOP_HESSIANMULTADJOINT=8)
      parameter(PETSCFNOP_HESSIANBUILD=9)
      parameter(PETSCFNOP_HESSIANBUILDADJOINT=10)
      parameter(PETSCFNOP_HESSIANBUILDSWAP=11)
      parameter(PETSCFNOP_SCALARAPPLY=12)
      parameter(PETSCFNOP_SCALARGRADIENT=13)
      parameter(PETSCFNOP_SCALARHESSIANMULT=14)
      parameter(PETSCFNOP_SCALARHESSIANBUILD=15)
      parameter(PETSCFNOP_CREATESUBFNS=16)
      parameter(PETSCFNOP_DESTROYSUBFNS=17)
      parameter(PETSCFNOP_CREATESUBFN=18)
      parameter(PETSCFNOP_CREATEDERIVATIVEFN=19)
      parameter(PETSCFNOP_DESTROY=20)
!
!  End of Fortran include file for the PetscFn package in PETSc
!
#if defined(_WIN32) && defined(PETSC_USE_SHARED_LIBRARIES)
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATEVECS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATEMATS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_APPLY
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_JACOBIANMULT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_JACOBIANMULTADJOINT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_JACOBIANBUILD
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_JACOBIANBUILDADJOINT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_HESSIANMULT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_HESSIANMULTADJOINT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_HESSIANBUILD
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_HESSIANBUILDADJOINT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_HESSIANBUILDSWAP
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARAPPLY
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARGRADIENT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARHESSIANMULT
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_SCALARHESSIANBUILD
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATESUBFNS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_DESTROYSUBFNS
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATESUBFN
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_CREATEDERIVATIVEFN
!DEC$ ATTRIBUTES DLLEXPORT::PETSCFNOP_DESTROY
#endif
