-include ../../../../../petscdir.mk
ALL: lib

CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  =
DIRS     = dgnet
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMNetwork
LOCDIR   = src/dm/impls/network/tutorials/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
