-include ../../../petscdir.mk

DIRS    = interface tests space dualspace fe fv riemannsolver netrs
MANSEC  = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
