-include ../../../../../../../petscdir.mk
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/dm/dt/riemannsolver/impls/lax/tests/
EXAMPLESC       = ex1.c
EXAMPLESF       =
MANSEC          = DM
SUBMANSEC       = RS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
