-include ../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = rs.c rscreate.c rsreg.c rsregall.c
SOURCEF   =
SOURCEH   =
DIRS      = 
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = RS
LOCDIR    = src/dm/dt/riemannsolver/interface

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

