
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = petscfn.c fnreg.c dlregisfn.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscfn
MANSEC   = Fn
LOCDIR   = src/fn/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
