ALL: lib

DIRS     = ipm admm almm mad
LOCDIR   = src/tao/constrained/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

