-include ../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = 
SOURCEF   =
SOURCEH   =
DIRS      = lax
LIBBASE   = 
MANSEC    = DM
SUBMANSEC = RS
LOCDIR    = src/dm/dt/riemannsolver/impls

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

