-include ../../../../../petsckdir.mk

SOURCEC	= utility.c
MANSEC	= Sys
LIBBASE	= libpetscsys
LOCDIR	= src/sys/objects/device/util/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

