-include ../../../../../petsckdir.mk

SOURCEC   = managedtype_c.c utility.c
SOURCEH   = ../interface/managedtype.inl
MANSEC	  = Sys
LIBBASE	  = libpetscsys
DIRS	  =
LOCDIR	  = src/sys/objects/device/util/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

