-include ../../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCECXX = femfem.cxx
SOURCEF   =
LIBBASE   = libpetscdm
DIRS      =
LOCDIR    = src/dm/dt/fe/impls/mfmem/
MANSEC    = DM
SUBMANSEC = FE

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
