
CFLAGS   =
FFLAGS	 =
CPPFLAGS =
FPPFLAGS =
LOCDIR	 = src/mat/examples/tests/suitesparse

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
