-include ../../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = lax.c
SOURCEF   =
SOURCEH   =
DIRS      = tests
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = RS
LOCDIR    = src/dm/dt/riemannsolver/impls/lax

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

