#requirespackage 'PETSC_HAVE_GRID'
-include ../../../../../petscdir.mk

SOURCECXX = plexGrid.cxx
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = DMPlex

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test