
CFLAGS		 =
FFLAGS		 =
CPPFLAGS   =
FPPFLAGS   =
LOCDIR		 = src/fn/examples/tests/
MANSEC     = Fn
EXAMPLESC	 = ex1.c

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
