
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fnshell.c fnshelltypes.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscfn
MANSEC   = Fn
LOCDIR   = src/fn/impls/shell/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
