#requiresscalar    real
ALL: lib

DIRS     = objective lagrangian auglag logbarrier
LOCDIR   = src/tao/merit/impls/
LIBBASE  = libpetsctao

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

