#requirespackage 'PETSC_HAVE_LIBAXB'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vecaxb.c vecaxb2.c
SOURCECU =
SOURCEF  =
SOURCEH  = vecaxbimpl.h
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/impls/seq/seqaxb/
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
