
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = ../../include/petscfn.h
LIBBASE  = libpetscfn
DIRS     = interface impls examples f90-mod utils
LOCDIR   = src/fn/
MANSEC   = Fn

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

