-include ../../../../petscdir.mk
CFLAGS	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/ml/dr/tests/
EXAMPLESC       = ex1.c
EXAMPLESCXX     =
EXAMPLESF       =
DIRS	          =
MANSEC          = ML
SUBMANSEC       = DR

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
