-include ../../../../../../petsckdir.mk
#requirespackage 'PETSC_HAVE_HIP'

SOURCEHIP = vecseqcupm.hip.cpp
SOURCEF   =
LIBBASE   = libpetscvec
MANSEC    = Vec
LOCDIR    = src/vec/vec/impls/seq/cupm/hip/
DIRS      =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
