#requirespackage 'PETSC_HAVE_LIBAXB'
ALL: lib

CFLAGS   = 
FFLAGS   =
SOURCEC  = mpihybrid.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/impls/mpi/mpihybrid/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
