-include ../../../../../../petsckdir.mk
#requirespackage 'PETSC_HAVE_CUDA'

SOURCECU = vecseqcupm.cu
SOURCEF  =
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/impls/seq/cupm/cuda/
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
