
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = fnutils.c
SOURCEF  =
SOURCEH  = fnutils.h
LIBBASE  = libpetscf
DIRS     =
MANSEC   = Fn
LOCDIR   = src/mat/utils/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

