
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = objective.c
SOURCEF   =
SOURCEH   = 
LIBBASE   = libpetsctao
MANSEC    = Tao
SUBMANSEC = TaoMerit
LOCDIR    = src/tao/merit/impls/objective/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

