ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = taovmnos.c
SOURCEF  =
SOURCEH  = taovmnos.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/unconstrained/impls/vmons/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

