
ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS =
SOURCEC  = faij.c
SOURCEF  =
SOURCEH  = faij.h
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat
LOCDIR   = src/mat/impls/faij/seq/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
