ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pdas.c
SOURCEF  =
SOURCEH  = pdas.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/constrained/impls/as/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

