-include ../../../../petscdir.mk

MANSEC		 = Tao
CLEANFILES       = eptorsion1 eptorsion2 minsurf2 rosenbrock1 eptorsion2f rosenbrock1f rosenbrock2 rosenbrock3

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules

rosenbrock1.o: rosenbrock1.h

rosenbrock1cu.o: rosenbrock1.h

