-include ../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = netrs.c netrsreg.c netrscreate.c 
SOURCEF   =
SOURCEH   =
DIRS      = 
LIBBASE   = libpetscdm
MANSEC    = DM
SUBMANSEC = NRS
LOCDIR    = src/dm/dt/netrs/interface

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

