-include ../../../../petscdir.mk
ALL: lib

SOURCEH   = ../../../../include/petsc/private/riemannsolverimpl.h ../../../../include/petscriemannsolver.h
DIRS      = interface impls tests
LOCDIR    = src/dm/dt/riemannsolver
MANSEC    = DM
SUBMANSEC = RS

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

