-include ../../../../petscdir.mk
#requiresscalar    real
#requirespackage   'PETSC_USE_FORTRAN_BINDINGS'

LIBBASE = libpetscml

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules_doc.mk
