-include ../../../../../petscdir.mk
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCEC   = basic.c
SOURCEF   =
SOURCEH   =
DIRS      = 
LIBBASE   = 
MANSEC    = DM
SUBMANSEC = NRS
LOCDIR    = src/dm/dt/netrs/impls

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

