-include ../../petscdir.mk
ALL: lib

SOURCEH  =
DIRS     = dr regressor
LOCDIR   = src/ml/
MANSEC   = ML

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
