#requirespackage 'PETSC_HAVE_LIBAXB'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = vechybrid.c vechybrid2.c
SOURCECU =
SOURCEF  =
SOURCEH  = vechybridimpl.h
LIBBASE  = libpetscvec
MANSEC   = Vec
LOCDIR   = src/vec/vec/impls/seq/seqhybrid/
DIRS     =

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
